name: Update gh-pages dependency

on:
  push:
    branches:
      - master

jobs:
  update-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies and update package
        run: |
          npm install
          npm install emoji-picker-react@latest

      - name: Build
        run: npm run build

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "updating package"
          branch: gh-pages
